### PR TITLE
chore: whitespace change to trigger ci/cd action

### PR DESCRIPTION
**Pull request by bryantbiggs**

### CODE REVIEW

**Comment by bryantbiggs** [comment]
@antonbabenko just doing a sanity check - looks to be working ok 👍🏼

**Comment by bryantbiggs** [comment]
looks like we have to bump the minimum terraform version for `terraform-aws-lambda` though https://github.com/terraform-aws-modules/terraform-aws-lambda/runs/1947301594

**Comment by antonbabenko** [comment]
We can bump it, but the problem with `terraform fmt` is happening from time to time in various versions, so the `master` branch should be only compatible with the `max` version of Terraform we support.

**Comment by antonbabenko** [comment]
Lambda's GH action looks good. Could you copy it to this one also?

**Comment by bryantbiggs** [comment]
opened #133 to update

**Pull request closed without merging**
