### PR TITLE
feat: Support `desired_capacity_type` and add mixed instance launch template override `instance_requirements` for ASG 

### PR DESCRIPTION
**Pull request by magreenbaum**
## Description
Add `desired_capacity_type` and mixed instance launch template override `instance_requirements` for ASGs. 

## Motivation and Context
https://github.com/hashicorp/terraform-provider-aws/pull/24795
https://github.com/hashicorp/terraform-provider-aws/issues/21566

## Breaking Changes
No. 

## How Has This Been Tested?
- [x] I have updated at least one of the `examples/*` to demonstrate and validate my change(s)
- [x] I have tested and validated these changes using one or more of the provided `examples/*` projects

- [x] I have executed `pre-commit run -a` on my pull request

### CODE REVIEW

**Comment by magreenbaum** [comment]
Unstale

**Comment by bryantbiggs** [comment]
whoops - sorry, I forgot about this one. I've marked it to take a look tomorrow

**Review by bryantbiggs — APPROVED** [review]
This looks awesome, thank you! (and thank you for your patience 😅 )

**Comment by antonbabenko** [comment]
This PR is included in version 6.8.0 :tada:

**Pull request merged**
