### PR TITLE
Add lifecycle hooks create_before_destroy to the autoscaling group

### PR DESCRIPTION
**Pull request by jherediacmp**

### CODE REVIEW

**Comment by antonbabenko** [comment]
There were multiple PRs like this - https://github.com/terraform-aws-modules/terraform-aws-autoscaling/pulls?utf8=%E2%9C%93&q=is%3Apr+is%3Aclosed+create_before_destroy

So far nobody proved to me that if we put them they will actually do what you expect from them. Tell me that I am wrong and I will surely accept this PR.

**Comment by jherediacmp** [comment]
My bad for not checking first , other PRs similar to this.

My use case is likely to https://github.com/terraform-aws-modules/terraform-aws-autoscaling/pull/18 , in the case that i create a new AMI with packer, and use terraform to deploy it.

I have interpolated both lc_name and asg_name , to use ami name, getting always the latest one , the one that i recently built with packer.

The launch configuration, as it has create_before_destroy lifecycle , is created for the new ami before destroying the existing , old one. The asg , as it doesnt have create_before_destroy lifecycle, is killed before creating the new asg , thus having a few minutes which i dont have live instances, thats downtime.

Not sure if i have explained good enough , let me know if you need some clarification.

As i saw you didnt accept similar PR , im perfectly fine if you dont accept this also. 

Thanks

**Comment by antonbabenko** [comment]
Well, after some more thinking I could not find downsides from merging this PR, so I decided to merge it **because** a lot of users asked for this in the past and I hope this will be helpful for everyone.

**Comment by antonbabenko** [comment]
[v2.6.0](https://github.com/terraform-aws-modules/terraform-aws-autoscaling/releases/v2.6.0) has been released.

**Pull request merged**
