### PR TITLE
[Breaking Changes] Use Launch Template

### LINKED ISSUE #44: Desired capacity should not be mandatory
Hello, first of all thanks for your module.

The `desired_capacity` parameter should not be mandatory, although I know that currently there is no way in Terraform to pass _null values_ to a module.
My use case is that I don't want to set written in stone in Terraform a desired capacity value for my ASG, or otherwise I could not apply Terraform when the ASG has auto-scaled to a different value.

### LINKED ISSUE #54: launch templates support
AWS provided the new way of defining instance setup with launch templates (not launch configurations). This is also supported by ASG [2].

It would be very helpful if launch templates [1] would also be supported - maybe even a new terraform-aws-launch-templates module would make sense.

[1] https://www.terraform.io/docs/providers/aws/r/launch_template.html
[2] https://www.terraform.io/docs/providers/aws/r/autoscaling_group.html

### PR DESCRIPTION
**Pull request by michaelaw320**
# Description

Convert Autoscaling Group to use `Launch Template` instead of `Launch Configuration`

Fixes #54 #81 
and possibly fixes #44 

This is backport from https://github.com/HENNGE/terraform-aws-autoscaling-mixed-instances . The said repository must use `Launch Template` to support mixed instance policy, so I decided to why not I backport the changes I made as I see more than 1 issue here requesting to use `Launch Template` with normal Autoscaling Group.

This will introduce breaking changes on input variables:
* `create_lc` is changed to `create_lt`
* `launch_configuration` changed to `launch_template`
* parameters which has `lc` is changed to `lt` (naming sense)
* `root_block_device`, `ebs_block_device`, `ephemeral_block_device` changed to `block_device_mappings` 

This PR tries to keep the behaviour the same (except for few inevitable changes above) and keep the changes minimal. Also this PR has not added features that becomes possible when using `Launch Template` (advanced network configurations, spot market configurations, etc.)

Currently I have no intention of supporting both `Launch Configuration` and `Launch Template` in the same module, it will make it complicated, and I see `Launch Template` supersedes `Launch Configuration` features, if there's anyone who is willing to support both, please close this PR and go with that PR instead 🙇

### CODE REVIEW

**Comment by acsrujan** [comment]
Should we support launch template versions and setting a version as _default_ in this PR?

**Comment by jwhitcraft** [comment]
ping @antonbabenko can we get a review on this?

**Comment by bryantbiggs** [comment]
thanks @michaelaw320 for the PR! I don't know if we can proceed with just replacing the launch config with the launch template as this module is widely used in the launch config version. I think we have two possible routes (in my opinion):

1. Updating the module to provide the option to use either launch config OR launch template. This would be quite an undertaking and should in theory support using the launch config as the default
2. Create a second module for autoscaling group that uses the launch template

Personally, I am more in favor of item 1 but it will take some work and a bit of testing to get it right. Thoughts? Feedback?

**Comment by yogeek** [comment]
@bryantbiggs Seems to me that option 1 is more flexible indeed and would allow a smoother transition for legacy code to go towards launch_template.
Is there any current work on this or is it currently paused ?
Thanks

**Comment by dawidmalina** [comment]
Having this will allow us to use gp3 - looks like launch configuration is not (yet) supported: https://github.com/hashicorp/terraform-provider-aws/issues/16514

**Pull request closed without merging**
