### PR TITLE
feat: add support for "kms_key_id" property in "ebs_block_device" and "root_block_device"

### PR DESCRIPTION
**Pull request by sisivy**
## Description
Add support for custom kms key for ebs and root block

## Motivation and Context
Actually it is not possible to use custom kms key

### CODE REVIEW

**Comment by sisivy** [comment]
See: https://www.terraform.io/docs/providers/aws/r/instance.html#kms_key_id-1

**Comment by bryantbiggs** [comment]
thanks for the PR @sisivy - would you mind making a few changes please:
- merge/rebase with master to update your branch to latest
- change your pr title to something like `feat: add support for "kms_key_id" property in "ebs_block_device" and "root_block_device"`
- update the `asg_ec2` example to show/test usage

**Comment by bryantbiggs** [comment]
@antonbabenko :+1:

**Comment by antonbabenko** [comment]
I deleted this release because this feature is not working as expected.

**Comment by bryantbiggs** [comment]
@antonbabenko could you share what the error or issue was?

**Comment by antonbabenko** [comment]
#116

I checked [CHANGELOG](https://github.com/terraform-providers/terraform-provider-aws/blob/release/2.x/CHANGELOG.md) before the merge but didn't find anything there, but still merged. My bad, I should have verified it, too.

**Comment by bryantbiggs** [comment]
oh thats my bad - the link provided shows the instance resource, this attribute is not available on the launch configuration resource

**Comment by antonbabenko** [comment]
no problems 👍

**Pull request merged**
