### PR TITLE
fix: Errors on `ignore_desired_capacity_changes = true` with mixed_instances_policy

### PR DESCRIPTION
**Pull request by smaruy30**
## Description
fix: Errors on ignore_desired_capacity_changes = true with mixed_instances_policy

## Motivation and Context
Configured the `mixed_instances_policy` object just like the [example](https://github.com/terraform-aws-modules/terraform-aws-autoscaling/blob/300379dda611504d78be058d56b132c2baaa1157/examples/complete/main.tf#L525) shows,
but encounterd the following errors while applying an autoscaling group with `ignore_desired_capacity_changes = true`.

    ```
    Error: Invalid function argument

      on .terraform/modules/asg/main.tf line 468, in resource "aws_autoscaling_group" "idc":
     468:             instance_type     = lookup(override.value, "instance_type", null)
        ├────────────────
        │ override.value is tuple with 6 elements

    Invalid value for "inputMap" parameter: lookup() requires a map as the first argument.

    Error: Invalid function argument

      on .terraform/modules/asg/main.tf line 469, in resource "aws_autoscaling_group" "idc":
     469:             weighted_capacity = lookup(override.value, "weighted_capacity", null)
        ├────────────────
        │ override.value is tuple with 6 elements

    Invalid value for "inputMap" parameter: lookup() requires a map as the first argument.
    ```

If you set `ignore_desired_capacity_changes = false` with the same mixed_instance_policy, then terraform apply does not report these errors.

## Breaking Changes
There are no breaking changes. It is a bug fix.

## How Has This Been Tested?
- [x] I have tested and validated these changes using the `mixed_instance` module in the provided `examples/complete` project (with `ignore_desired_capacity_changes = true` set)

Tested with Terraform v1.1.4

### CODE REVIEW

**Comment by smaruy30** [comment]
@bryantbiggs 
This MR is not proceeding for 2weeks.
Can you suggest me any actions missing from me?

**Comment by bryantbiggs** [comment]
@smaruy30 we'll need a reproduction showing the issue and then that will most likely get added as a test case so we can validate and sure functionality is maintained going forward

**Comment by antonbabenko** [comment]
This issue has been resolved in version 6.0.0 :tada:

**Comment by smaruy30** [comment]
@antonbabenko Thanks for the update!

**Pull request closed without merging**
