### PR TITLE
feat: Add support for `warm_pool`

### PR DESCRIPTION
**Pull request by curiositycasualty**
## Description
Adds support for `aws_autoscaling_group`'s `warm_pool` configuration.

## Motivation and Context
This isn't a hill I need to die on. If this change is risky for some reason that's non-obvious to me, we can forego a merge of this.

## Breaking Changes
This is a relatively new feature to the underlying `aws` provider: https://github.com/hashicorp/terraform-provider-aws/pull/18734

## How Has This Been Tested?
- [x] I have tested and validated these changes using one or more of the provided `examples/*` projects

See supplied example.

### CODE REVIEW

**Comment by bryantbiggs** [comment]
hey thanks for the PR @curiositycasualty ! I think this looks great, I'll find some time to test and validate. one thing we'll need to update is the min AWS provider version to 3.37.0 per https://github.com/hashicorp/terraform-provider-aws/pull/18734#issuecomment-821296130

**Comment by sudermanjr** [comment]
I just found this feature, and it might be just what I need. Any chance of this getting updated per review and added in?

**Comment by verejoel** [comment]
+1 for seeing this revived, definitely would like to use this feature!

**Comment by curiositycasualty** [comment]
@bryantbiggs Have you had a change to poke this? I just rebased and got things "semantic".

**Comment by denraf** [comment]
@curiositycasualty What @bryantbiggs was saying is to update the aws minimum version requirement in `versions.tf`
```suggestion
      version = ">= 3.37"
```

**Comment by curiositycasualty** [comment]
Thanks @denraf. Sorry for the delay.

**Comment by curiositycasualty** [comment]
@bryantbiggs This is ready for review.

**Comment by bryantbiggs** [comment]
apologies, looks good if you can fix the conflicts and rebase `master` - 👍🏽 @antonbabenko 
image

**Comment by antonbabenko** [comment]
Thanks @curiositycasualty for the PR!

[v4.6.0](https://github.com/terraform-aws-modules/terraform-aws-autoscaling/releases/v4.6.0) has been just released.

**Pull request merged**
