### PR TITLE
fix: Ignore changes to `load_balancers` and `target_group_arns`

### PR DESCRIPTION
**Pull request by bryantbiggs**
## Description
- Ignore changes to `load_balancers` and `target_group_arns`
- Ref https://github.com/hashicorp/terraform-provider-aws/issues/14540

## Motivation and Context
- Resolves #250

## Breaking Changes
- No

## How Has This Been Tested?
- [ ] I have updated at least one of the `examples/*` to demonstrate and validate my change(s)
- [ ] I have tested and validated these changes using one or more of the provided `examples/*` projects

- [x] I have executed `pre-commit run -a` on my pull request

### CODE REVIEW

**Review by antonbabenko — COMMENTED** [review]
I tried to comprehend all the messages that were posted on this and linked issues and I don't understand WHY do we want to ignore changes in these additional arguments? They seem to be very important and it should have been addressed in the Terraform AWS provider, if their behavior is not consistent.

Am I missing something? Could you please explain briefly why this change is needed to be fixed in the module and not in provider?

**Comment by dusansusic** [comment]
also, @antonbabenko and @bryantbiggs from [this doc](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/guides/version-3-upgrade#resource-aws_autoscaling_group) we can find:
```
If aws_autoscaling_attachment resources reference your ASG configurations, you will need to add the [lifecycle configuration block](https://www.terraform.io/docs/configuration/meta-arguments/lifecycle.html) with an ignore_changes argument to prevent Terraform non-empty plans (i.e., forcing resource update) during the next state refresh.
```

**Review by antonbabenko — APPROVED** [review]
Thanks for the brief explanation, @dusansusic ! It is very clear to me now. Time to merge. 👌

**Comment by antonbabenko** [comment]
This PR is included in version 7.3.1 :tada:

**Comment by kkumtree** [comment]
I appreciate that my (but failed) pull request motivated you to make your pull request.

**Pull request merged**
